# Generated by Django 5.0.7 on 2024-12-09 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmCoP', '0004_contactmessage_delete_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.')])),
                ('location', models.CharField(max_length=255)),
                ('emergency_type', models.CharField(choices=[('medical', 'Medical Emergency'), ('accident', 'Accident'), ('fire', 'Fire'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
